### PR TITLE
added json format and keys

### PR DESCRIPTION
**Pull request by sjmittal**
added special case for unwrapped message for json format and key

### CODE REVIEW

**Comment by sjmittal** [comment]
@andrewstevenson  Well I have added some tests but looks like I cannot run test cases on windows using gradle. Or maybe I am not following correct procedure to run test cases. Can you guide me on the steps to run test cases for a single project (or specific test cases).

**Comment by andrewstevenson** [comment]
@sjmittal run them in WSL. I've just switched back to Windows from Mac and also have some issues with the cassandra tests, its probably because we start and embedded cassandra instance

**Comment by sjmittal** [comment]
@andrewstevenson Due to some space constraints I am unable to run them in WSL. I know windows have an issue when running test case, but I seemed to have fixed that and now the tests as failing with error:
`Error: Could not find or load main class org.scalatest.tools.Runner`

I have logged an issue for this at:
https://github.com/maiflai/gradle-scalatest/issues/82

Lets see what the response is. I feel tests should run in windows env too.

**Comment by sjmittal** [comment]
@andrewstevenson  I have added few test cases.

**Comment by andrewstevenson** [comment]
@sjmittal Can you update the readme? Then we are good to go.

**Comment by sjmittal** [comment]
@andrewstevenson Could you please tell me which file to update for readme because I don't see any readme file under:
https://github.com/lensesio/stream-reactor/tree/master/kafka-connect-cassandra

**Comment by andrewstevenson** [comment]
@sjmittal The root README of the whole streamreactor. https://github.com/lensesio/stream-reactor/blob/master/README.md

**Comment by andrewstevenson** [comment]
@sjmittal add a pending section in the release notes

**Comment by sjmittal** [comment]
@andrewstevenson  I have added a readme note for this new feature.

**Pull request merged**
