### PR TITLE
converter for mqtt sink connector

### PR DESCRIPTION
**Pull request by smaXtecStefan**
added converter for mqtt sink connector.

we are using avro serialized messages in our mqtt system.

### CODE REVIEW

**Comment by andrewstevenson** [comment]
@smaXtecStefan Can you check the build failure?

**Comment by smaXtecStefan** [comment]
It seems that the test in JMSReaderTest.scala ("should read message from JMS queue without converters") randomly fails. in one of my roughly 10 test runs the test failed.

**Comment by andrewstevenson** [comment]
@smaXtecStefan Ok, build looks good, if you address the two comments on the test we are good

**Comment by smaXtecStefan** [comment]
> @smaXtecStefan Ok, build looks good, if you address the two comments on the test we are good

I'm not sure what you mean. where should I add those comments?

**Comment by andrewstevenson** [comment]
@smaXtecStefan I left some review comments for the tests.

**Comment by smaXtecStefan** [comment]
@andrewstevenson  I can't find the comments. Where do I see them?

**Comment by andrewstevenson** [comment]
@smaXtecStefan above :-) 
image

**Comment by smaXtecStefan** [comment]
@andrewstevenson thank you for the screenshot. for some reason the comments are not visible for me. is it possible, that the "Submit review" button from the screenshot needs to be pressed?

**Comment by andrewstevenson** [comment]
@smaXtecStefan :-)

**Pull request merged**
